language: ruby
rvm:
- 2.5.1
sudo: required
services:
- docker
before_script:
- IMAGE_NAME=numascott/pie-website:$(git log -1 --pretty=%H)
- echo $IMAGE_NAME
- docker build -t $IMAGE_NAME .
script:
- docker run --rm -d --name pie-website-instance -p 4000:4000 $IMAGE_NAME
- docker ps -a
- sleep 5
- curl localhost:4000
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push $IMAGE_NAME
after_script:
- docker stop pie-website-instance
env:
  global:
  - secure: VYnXZuaawE/FdmNqSL57eSFut/bgyF3VWiGAoSdSE7f+cqadP5hFuWQdOidWjB8IgMMDR6R1I3C27/7hUr5yQ02D4pyu92auGFFIE4GwtsLsIjmGwzgBMKq0wkJvb9YjHAz75ZYY+jJSsoWocQxnC75tV6WNsHzyGSZ3A2Qq7JAaFmii+E9nmHFiB20SQPAuXbs616GsLzDBeI44C+WeIDfn+Pq2iEbkdCrZ7jw4TWmOkBjPePzenSOmSIuUN/rBzUMddbcGgmAaR6ZPaojIEdFRgN403yJwds8e1CoBM2n7hIl5U+IFFp2U2Tf0ZDNBgXmwdS3d4EQJIwIYFRhTDvK+RIe512owVR5sAHdHv3yk0hwPrng8QV85mzC857WW5M1UrCIfL9N2Ztep3pCMMg1VP8Ik+aNB6WNvOJVHhnGACQ/KDv3qJKlFGt09vw/LNWzHU8xUwyIq6OaMwfVjh6XPfIUl4SdQP4fDNh+njwpKAnkdZ1WvcB/csHWAZBZ+w9di5coD4T35ABqxCwNxea3pwxgnXw1BhUfCsze902QpBWYzg4kfuDN9suM+E9Bw9tSNLyLzbaGp1Dallig7a3DHJxFqa351kx+ndXu7MxecmCztaLRrVO1kK0LOv/VeLPIVXmkou0Zbqt6/vZTrBqReytfDrYtqT1chMl0kYhc=
  - secure: jPrDvR4nszMFoWqJ6ZfMsZ6bKMY9LGAc4sCIHdvVoUrI1XKYTMxFBRQnGZWcdT1A3NBOppY8nCS8GFRqdhOctcoqXWmUivH+msDzTL0u7n9+1ABeUMzilsnKW+kJwfEwu99HkkKavgj8hlgcBupTFbIWzKLuho07EcAIdOEKYT2sBcU4PM0kyaLwYh/UpI7HOy12XtQ6zFqVy+taWmPtn8hOft2wvb8yHLtm0nKZVUcvvcTz8Hb5p4c0HPFyMji9zo31yX3RfuU7mwn4V/E1/6l07tTa/apSfsADjwV3+/GYurpopM61eQCUXnsEAq5lFNKdmNF0+ui/dp0VcIFuqFfs+I+r0X8yI4GCk0ouI8mhICYu4RF/Ffs+Ty+4L2CHl4Q4vk/J4rD1uUOqNutZiUFJMstp6xrDTMxR75wodNP4gFWKFnBHJPEtHQyAruFVqnkwK30HwuvMvBNJIZ/fYuvgJpcTsAJXxF4dTAlFk3N/rgmme8/cdWXKHeRBAhsKBYze/NTSEYrp2dplbvpWVK6wO6ZA9N2VcJH3z1/ql31NlHy/viW6BA+ytMVPt+eX4Q5nUrSLKOjsv3Skim2gDWwFQGkaWHSWsnBTH1h6epklrpjA1ijHFoxkX0nERt7cVftTnPPLC9jwTfYhAmkrTKOpCLrV18PUPlySte8ZeB0=
