language: ruby
rvm:
- 2.5.1
sudo: required
services:
- docker
before_script:
- IMAGE_NAME=numascott/pie-website:$(git log -1 --pretty=%H)
- echo $IMAGE_NAME
- docker build -t $IMAGE_NAME .
script:
- docker run --rm -d --name pie-website-instance -p 4000:4000 $IMAGE_NAME
- docker ps -a
- sleep 5
- curl localhost:4000
after_success:
- echo "$DOCKER_PASSWORD" | docker login -u "numascott" --password-stdin
- docker push $IMAGE_NAME
after_script:
- docker stop pie-website-instance
env:
  global:
    secure: dh4vNspiShjOEmJJE0/YGA3CO1RDO+Ws9WKXyJBOJlVfCqSjQe/feqzem2L2rAPHjF/5NgOqsTeie0sA0EVvzIe9MJVjRR9HJdI7L/X0XMWks/SKQ+90wpjGJxQesIzcFl/55Bx5+it8XW2a2/t3BhyqvX85NAkI9oZZqsU/YJWydGsWcDJXH/y1zmsUEP9nyfIW6z6VS/bMtw8zN765n/5vdBfLnzk9dAU1GWUXAiwK1bDzmVTZS/64Ri6G0WAANZgCyDRHrSKAwWw6ctdI1Nma3ENtk2RAe/uQiSgL0YYXZVn0DLyBjwL4yyyTeG8p9PATRyae2ghtPqUAgsaGYqpn/BrRYH9br+7PS1GBbv6uoj0T1GISuGFGU9Gb6xmS/rO6CrwfCDoVdfSF4nFLGr7uJ2Wba5vYZzw7e9WtkRkqK6OhqSEtOtwF7Rq25ZiodbG/jhhxWG9Dx4XfQATdiuVJiK2q6tNqXrg3mn9O8nEMKo4GtH4C4jEjmUkRBVYaFna6dmc4Y1/C50IR9k8DbjYG3Ap5J5bqDM+VVFaRHcS+iQ8ZZwbPPgZ+Mnf/qBOQVAZ3IlY6DBxRUqXGue2kL88ja6ZmDVTGl0ej5cEAPVAytncStX6NHVqicj0pUpnnVpJVyjZuOcaBeMPZrYFKkNJEn2OWUCiNFxkECE0+rqo=
